### ISSUE TITLE
Unhandled event: updateOrientation

### ISSUE THREAD

**Issue by rommyarb** [paulsonnentag/swip#44]
Hello. I was running the Particles demo with 2 android devices both have 4.5 inch screen. It was going well at begining, I add few particles, then suddenly server dismissed, and this error shown:

Unhandled event: updateOrientation
Error: Unhandled event: updateOrientation
    at clientAction (D:\github\swip-master\src\server\reducer.js:77:13)
    at D:\github\swip-master\src\server\reducer.js:22:16
    at dispatch (D:\github\swip-master\node_modules\redux\lib\createStore.js:179:22)
    at Object.e [as dispatch](D:githubswip-mastersrcserverdebug-middleware.js:12:18)
    at Socket.socket.on (D:\github\swip-master\src\server\index.js:30:59)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.onevent (D:\github\swip-master\examples\particles\node_modules\socket.io\lib\socket.js:348:8)
    at Socket.onpacket (D:\github\swip-master\examples\particles\node_modules\socket.io\lib\socket.js:308:12)
    at Client.ondecoded (D:\github\swip-master\examples\particles\node_modules\socket.io\lib\client.js:194:14)

Am I doing it wrong. Please help me fix this. Thank you :D

**Comment by paulsonnentag** [comment]
The problem is probably on our side. I'll look into it later.

**Comment by hdkcreative** [comment]
hi ! any solution  ?
